### ISSUE TITLE
Cannot run code

### ISSUE THREAD

**Issue by lefreud** [JustinHogue/SkinDetector#1]
I pulled the master branch but I was unable to run the code on my Windows computer... Can someone help??

**Comment by JustinHogue** [comment]
Could you please add a screenshot of the error in the console?

**Comment by lefreud** [comment]
![image](https://user-images.githubusercontent.com/35122940/164996550-16f3edcf-6781-456f-9f45-4527fc2db6fb.png)

Please review this critical bug ASAP

**Comment by JustinHogue** [comment]
You actually need to clone the repo sir. Marked as solved.
